/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.alper_celik.java_examples.second_term.forms;

/**
 *
 * @author alper
 */
public class second_frame extends javax.swing.JFrame {

    /**
     * Creates new form second_frame
     */
    public second_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bm_eng = new javax.swing.JCheckBox();
        sonuc_label = new javax.swing.JLabel();
        ym_eng = new javax.swing.JCheckBox();
        yz_eng = new javax.swing.JCheckBox();
        bsm_eng = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bm_eng.setText("Bilgisayar Mühendisliği");
        bm_eng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bm_engActionPerformed(evt);
            }
        });

        sonuc_label.setText("jLabel1");
        sonuc_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ym_eng.setText("Yazılım Mühendisliği");
        ym_eng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ym_engActionPerformed(evt);
            }
        });

        yz_eng.setText("Yapay Zeka Mühendisliği");
        yz_eng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yz_engActionPerformed(evt);
            }
        });

        bsm_eng.setText("bilişim sistemleri mühendisliği");
        bsm_eng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsm_engActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sonuc_label, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(bm_eng)
                                                        .addComponent(yz_eng))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(bsm_eng)
                                                        .addComponent(ym_eng))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(sonuc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bm_eng)
                                        .addComponent(ym_eng))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(yz_eng)
                                        .addComponent(bsm_eng))
                                .addContainerGap(162, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bm_engActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bm_engActionPerformed
        update_label();
    }// GEN-LAST:event_bm_engActionPerformed

    private void ym_engActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ym_engActionPerformed
        update_label();
    }// GEN-LAST:event_ym_engActionPerformed

    private void yz_engActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_yz_engActionPerformed
        update_label();
    }// GEN-LAST:event_yz_engActionPerformed

    private void bsm_engActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bsm_engActionPerformed
        update_label();
    }// GEN-LAST:event_bsm_engActionPerformed

    private void update_label() {
        String text = "";
        if (ym_eng.isSelected()) {
            text += ym_eng.getText() + ", ";
        }
        if (bm_eng.isSelected()) {
            text += bm_eng.getText() + ", ";
        }
        if (bsm_eng.isSelected()) {
            text += bsm_eng.getText() + ", ";
        }
        if (yz_eng.isSelected()) {
            text += yz_eng.getText() + ", ";
        }
        sonuc_label.setText(text);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(second_frame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(second_frame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(second_frame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(second_frame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new second_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bm_eng;
    private javax.swing.JCheckBox bsm_eng;
    private javax.swing.JLabel sonuc_label;
    private javax.swing.JCheckBox ym_eng;
    private javax.swing.JCheckBox yz_eng;
    // End of variables declaration//GEN-END:variables
}
